// spas/angular/sample-app/src/app/components/auth-guarded-api/auth-guarded-api.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-auth-guarded-api',
  standalone: true,
  imports: [],
  templateUrl: './auth-guarded-api.component.html',
  styleUrl: './auth-guarded-api.component.scss'
})
export class AuthGuardedApiComponent {

}

<div class="container text-center mt-5">
    <h1 class="display-3">Auth guarded external api</h1>
</div>

// spas/vue/sample-app/src/components/AuthGuardedApiComponent.vue

<template>
    <div class="container text-center mt-5">
      <h1 class="display-3">Auth guarded external api</h1>
    </div>
  </template>
  
  <style scoped>
  .container {
    background-color: #f8f9fa;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  @import "bootstrap/dist/css/bootstrap.min.css";
  </style>
  
  <script></script>
